

#production:
 #adapter: postgresql
 #encoding: unicode
 #pool: 5

default:
  adapter: postgresql
  database: mydb
  username: theodor
  password: firstproject
  pool: 5
  encoding: unicode

#test:
#  database: db/test.sqlite3
